Optimizing Radeon VRAM behavior
===============================

[glossary]
Glossary
--------

[glossary]
buffer::
	A block of memory used for some purpose.

FPS::
	Frames per second, a common performance metric.

Frame time::
	The inverse of FPS, ie. (milli)seconds per frame.

RAM::
	Random Access Memory, a type of computer memory.

VRAM::
	Video RAM, fast on-board memory included on graphics cards.

Introduction
------------

Graphics cards carry some fast, dedicated memory (VRAM). This memory is used to speed up 
tasks such as rendering or parallel computations, by avoiding the latency in having the 
graphics card access the system memory.

VRAM is a limited resource, and as such, all workloads may not fit in a given graphics 
card. In a situation like that, the strategy that decides what parts of the working set to 
keep in VRAM, and which parts can be kept in regular system RAM, is of utmost importance.

If the application needs to access a specific resource in system RAM, it will have a 
corresponding hit in its performance. The VRAM placement strategy should try to rank the 
application's buffers in such a way to maximize the application's performance.

Application performance is commonly measured in two ways: throughput (FPS, frames per 
second) and responsiveness (how stable the FPS is). For a good user experience, they both 
must be above some user-dependent threshold.

There are no generally accepted guidelines, as the minimum for an acceptable experience is 
quite subjective. However, many people place the line at 60 FPS with a minimum FPS of 55.
(Minimum playable FPS, 2012)

Both throughput and smoothness must be above the user's minimum requirements, one alone will 
not suffice. For example, a game running at a healthy throughput of 60 FPS, but dipping to 
10 FPS once per second will be extremely irritating, perceived as stalling or stuttering. 
Vice versa, a smooth FPS of 20 will not stutter, but the throughput is not high enough for 
an enjoyable experience, as the user will notice individual images instead of the illusion 
of movement.

AI theory
---------

Fragmentation
-------------

Training the network
--------------------

Cost model
~~~~~~~~~~

Activation function
~~~~~~~~~~~~~~~~~~~

Results
-------

Discussion
----------

[bibliography]
Bibliography
------------

Minimum playable FPS. 2012. Whirlpool forums. Retrieved on Jan 15 2013. 
http://forums.whirlpool.net.au/archive/1890684
